CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Airlines" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(3) NOT NULL,
        "NameTr" character varying(100) NOT NULL,
        "NameEn" character varying(100) NOT NULL,
        "LogoUrl" character varying(255),
        "CountryCode" character varying(2),
        "Alliance" character varying(50),
        "IsDomestic" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        CONSTRAINT "PK_Airlines" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Airports" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "IataCode" character varying(3) NOT NULL,
        "IcaoCode" character varying(4),
        "NameTr" character varying(100) NOT NULL,
        "NameEn" character varying(100) NOT NULL,
        "CityTr" character varying(50) NOT NULL,
        "CityEn" character varying(50) NOT NULL,
        "CountryTr" character varying(50) NOT NULL,
        "CountryEn" character varying(50) NOT NULL,
        "CountryCode" character varying(2) NOT NULL,
        "Timezone" character varying(50),
        "Latitude" double precision,
        "Longitude" double precision,
        "CityCode" character varying(5),
        "Type" character varying(20),
        "Region" character varying(50),
        "IsCity" boolean NOT NULL,
        "IsDomestic" boolean NOT NULL,
        "IsPopular" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        CONSTRAINT "PK_Airports" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "FareTypes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(10) NOT NULL,
        "NameTr" character varying(50) NOT NULL,
        "NameEn" character varying(50) NOT NULL,
        "SortOrder" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_FareTypes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "GuestSessions" (
        "Id" uuid NOT NULL,
        "Email" text,
        "Phone" text,
        "IpAddress" text,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_GuestSessions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "PopularRoutes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "OriginCode" character varying(3) NOT NULL,
        "DestinationCode" character varying(3) NOT NULL,
        "DisplayPrice" numeric(18,2),
        "Currency" character varying(3) NOT NULL,
        "IsActive" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        CONSTRAINT "PK_PopularRoutes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Users" (
        "Id" uuid NOT NULL,
        "CustomerNumber" text NOT NULL,
        "Email" text NOT NULL,
        "PasswordHash" text NOT NULL,
        "FullName" text NOT NULL,
        "Phone" text,
        "Role" text NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "BookingClasses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" character varying(2) NOT NULL,
        "FareTypeId" integer NOT NULL,
        "NameTr" character varying(50) NOT NULL,
        "NameEn" character varying(50) NOT NULL,
        "IsRefundable" boolean NOT NULL,
        "IsChangeable" boolean NOT NULL,
        "SortOrder" integer NOT NULL,
        CONSTRAINT "PK_BookingClasses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingClasses_FareTypes_FareTypeId" FOREIGN KEY ("FareTypeId") REFERENCES "FareTypes" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Bookings" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "BiletBankFileId" uuid,
        "PNR" text,
        "InternalPnr" text,
        "Status" text NOT NULL,
        "GrandTotal" numeric,
        "Currency" text,
        "IsFinalized" boolean NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        "TransactionId" character varying(100),
        "Origin" character varying(3),
        "Destination" character varying(3),
        "AirlineCode" character varying(3),
        "FlightNumber" character varying(20),
        "SessionId" character varying(100),
        "SessionToken" character varying(100),
        "ProductItemId" character varying(100),
        "ServiceFee" numeric(18,2) NOT NULL,
        "OurCommission" numeric(18,2) NOT NULL,
        "AllocatedAt" timestamp without time zone,
        "BookedAt" timestamp without time zone,
        "PaidAt" timestamp without time zone,
        "TicketedAt" timestamp without time zone,
        "CancelledAt" timestamp without time zone,
        "LastError" text,
        "RetryCount" integer NOT NULL,
        "AdultCount" integer NOT NULL,
        "ChildCount" integer NOT NULL,
        "InfantCount" integer NOT NULL,
        "GuestSessionId" uuid,
        CONSTRAINT "PK_Bookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Bookings_GuestSessions_GuestSessionId" FOREIGN KEY ("GuestSessionId") REFERENCES "GuestSessions" ("Id"),
        CONSTRAINT "FK_Bookings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Sessions" (
        "Id" uuid NOT NULL,
        "BiletBankSessionId" character varying(100),
        "BiletBankSessionToken" character varying(100),
        "ShoppingFileId" character varying(100),
        "UserId" uuid,
        "IpAddress" character varying(50),
        "UserAgent" text,
        "Status" character varying(20) NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "ExpiresAt" timestamp without time zone,
        "LastActivityAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "SystemLogs" (
        "Id" uuid NOT NULL,
        "UserId" uuid,
        "SessionId" text,
        "Action" text NOT NULL,
        "Detail" text,
        "IpAddress" text,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SystemLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SystemLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Trips" (
        "Id" uuid NOT NULL,
        "UserId" uuid NOT NULL,
        "TripName" text,
        "TripType" text NOT NULL,
        "Origin" text NOT NULL,
        "Destination" text NOT NULL,
        "DepartureDate" timestamp without time zone NOT NULL,
        "ReturnDate" timestamp without time zone,
        "TotalPassengers" integer NOT NULL,
        "Status" text NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_Trips" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Trips_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "BillingInfo" (
        "Id" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        "BillingName" text NOT NULL,
        "TaxNo" text,
        "TaxOffice" text,
        "AddressCity" text,
        "AddressDistrict" text,
        "AddressDetail" text,
        "AddressZipCode" text,
        "CountryCode" text,
        "IsCompany" boolean NOT NULL,
        CONSTRAINT "PK_BillingInfo" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BillingInfo_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "BookingLogs" (
        "Id" uuid NOT NULL,
        "BookingId" uuid,
        "UserId" uuid,
        "SessionId" text,
        "SessionToken" text,
        "Operation" text NOT NULL,
        "RequestBody" text,
        "ResponseBody" text,
        "IsSuccess" boolean NOT NULL,
        "ErrorMessage" text,
        "IpAddress" text,
        "ResponseTimeMs" integer,
        "HttpStatusCode" integer,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_BookingLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingLogs_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id"),
        CONSTRAINT "FK_BookingLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "FareDetails" (
        "Id" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        "BaseFare" numeric(18,2) NOT NULL,
        "TotalTax" numeric(18,2) NOT NULL,
        "ServiceFee" numeric(18,2) NOT NULL,
        "GrandTotal" numeric(18,2) NOT NULL,
        "Currency" text NOT NULL,
        "BiletBankCost" numeric(18,2),
        "OurPrice" numeric(18,2),
        "Profit" numeric(18,2),
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_FareDetails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FareDetails_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "FlightSegments" (
        "Id" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        "SequenceNo" integer NOT NULL,
        "MarketingAirline" text NOT NULL,
        "OperatingAirline" text,
        "FlightNumber" text NOT NULL,
        "OriginCode" text NOT NULL,
        "DestinationCode" text NOT NULL,
        "DepartureDate" timestamp without time zone NOT NULL,
        "DepartureTime" text,
        "ArrivalDate" timestamp without time zone,
        "ArrivalTime" text,
        "BookingClass" text,
        "Cabin" text,
        "FareBasis" text,
        "Baggage" text,
        "TicketNumber" text,
        "Equipment" text,
        CONSTRAINT "PK_FlightSegments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_FlightSegments_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Passengers" (
        "Id" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        "SequenceNo" integer NOT NULL,
        "Type" text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        "Gender" text NOT NULL,
        "BirthDate" text NOT NULL,
        "CitizenNo" text,
        "PassportNo" text,
        "PassportCountry" text,
        "Nationality" text,
        "Email" text,
        "Phone" text,
        "HesCode" text,
        "TempTag" character varying(100),
        "PaxReferenceId" character varying(100),
        "TicketNumber" character varying(20),
        CONSTRAINT "PK_Passengers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Passengers_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "Payments" (
        "Id" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        "Amount" numeric(18,2) NOT NULL,
        "Currency" text NOT NULL,
        "CardHolderName" text,
        "MaskedCardNumber" text,
        "InstallmentCount" integer NOT NULL,
        "Status" text NOT NULL,
        "TransactionDate" timestamp without time zone NOT NULL,
        "CardLastFour" character varying(4),
        "CardHolder" character varying(100),
        "Is3DSecure" boolean NOT NULL,
        "RedirectUrl" text,
        "ProviderTransactionId" character varying(100),
        "ErrorMessage" character varying(500),
        "RefundedAt" timestamp without time zone,
        "RefundAmount" numeric(18,2),
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "SearchLogs" (
        "Id" uuid NOT NULL,
        "SessionId" uuid,
        "TransactionId" character varying(100),
        "Origin" character varying(3) NOT NULL,
        "Destination" character varying(3) NOT NULL,
        "DepartureDate" timestamp without time zone NOT NULL,
        "ReturnDate" timestamp without time zone,
        "FlightType" character varying(5),
        "FlightClass" character varying(20),
        "AdultCount" integer NOT NULL,
        "ChildCount" integer NOT NULL,
        "InfantCount" integer NOT NULL,
        "ResultCount" integer NOT NULL,
        "MinPrice" numeric(18,2),
        "ResponseTimeMs" integer,
        "HasError" boolean NOT NULL,
        "ErrorMessage" character varying(500),
        "IpAddress" character varying(50),
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SearchLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SearchLogs_Sessions_SessionId" FOREIGN KEY ("SessionId") REFERENCES "Sessions" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "TripBookings" (
        "Id" uuid NOT NULL,
        "TripId" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        CONSTRAINT "PK_TripBookings" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TripBookings_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TripBookings_Trips_TripId" FOREIGN KEY ("TripId") REFERENCES "Trips" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE TABLE "TripPassengers" (
        "Id" uuid NOT NULL,
        "TripId" uuid NOT NULL,
        "PassengerId" uuid NOT NULL,
        CONSTRAINT "PK_TripPassengers" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_TripPassengers_Passengers_PassengerId" FOREIGN KEY ("PassengerId") REFERENCES "Passengers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_TripPassengers_Trips_TripId" FOREIGN KEY ("TripId") REFERENCES "Trips" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (1, 'Star Alliance', 'TK', 'TR', TIMESTAMP '2026-04-15T21:49:05.969004', TRUE, TRUE, '/assets/airlines/tk.png', 'Turkish Airlines', 'Türk Hava Yolları', 1, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (2, NULL, 'PC', 'TR', TIMESTAMP '2026-04-15T21:49:05.969005', TRUE, TRUE, '/assets/airlines/pc.png', 'Pegasus Airlines', 'Pegasus Hava Yolları', 2, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (3, NULL, 'VF', 'TR', TIMESTAMP '2026-04-15T21:49:05.969005', TRUE, TRUE, '/assets/airlines/vf.png', 'AnadoluJet', 'AnadoluJet', 3, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (4, NULL, 'XQ', 'TR', TIMESTAMP '2026-04-15T21:49:05.969005', TRUE, TRUE, '/assets/airlines/xq.png', 'SunExpress', 'SunExpress', 4, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (5, NULL, 'XC', 'TR', TIMESTAMP '2026-04-15T21:49:05.969005', TRUE, TRUE, '/assets/airlines/xc.png', 'Corendon Airlines', 'Corendon Airlines', 5, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (6, 'Star Alliance', 'LH', 'DE', TIMESTAMP '2026-04-15T21:49:05.969005', TRUE, FALSE, '/assets/airlines/lh.png', 'Lufthansa', 'Lufthansa', 10, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (7, 'Oneworld', 'BA', 'GB', TIMESTAMP '2026-04-15T21:49:05.969005', TRUE, FALSE, '/assets/airlines/ba.png', 'British Airways', 'British Airways', 11, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (8, 'SkyTeam', 'AF', 'FR', TIMESTAMP '2026-04-15T21:49:05.969006', TRUE, FALSE, '/assets/airlines/af.png', 'Air France', 'Air France', 12, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (9, NULL, 'EK', 'AE', TIMESTAMP '2026-04-15T21:49:05.969006', TRUE, FALSE, '/assets/airlines/ek.png', 'Emirates', 'Emirates', 13, NULL);
    INSERT INTO "Airlines" ("Id", "Alliance", "Code", "CountryCode", "CreatedAt", "IsActive", "IsDomestic", "LogoUrl", "NameEn", "NameTr", "SortOrder", "UpdatedAt")
    VALUES (10, 'Oneworld', 'QR', 'QA', TIMESTAMP '2026-04-15T21:49:05.969006', TRUE, FALSE, '/assets/airlines/qr.png', 'Qatar Airways', 'Qatar Airways', 14, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    INSERT INTO "FareTypes" ("Id", "Code", "IsActive", "NameEn", "NameTr", "SortOrder")
    VALUES (1, 'ECO', TRUE, 'Economy', 'Ekonomi', 1);
    INSERT INTO "FareTypes" ("Id", "Code", "IsActive", "NameEn", "NameTr", "SortOrder")
    VALUES (2, 'PEF', TRUE, 'Premium Economy', 'Premium Ekonomi', 2);
    INSERT INTO "FareTypes" ("Id", "Code", "IsActive", "NameEn", "NameTr", "SortOrder")
    VALUES (3, 'BUS', TRUE, 'Business', 'Business', 3);
    INSERT INTO "FareTypes" ("Id", "Code", "IsActive", "NameEn", "NameTr", "SortOrder")
    VALUES (4, 'FIR', TRUE, 'First Class', 'First Class', 4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    INSERT INTO "PopularRoutes" ("Id", "CreatedAt", "Currency", "DestinationCode", "DisplayPrice", "IsActive", "OriginCode", "SortOrder", "UpdatedAt")
    VALUES (1, TIMESTAMP '2026-04-15T21:49:05.969046', 'TRY', 'AYT', 899.0, TRUE, 'IST', 1, NULL);
    INSERT INTO "PopularRoutes" ("Id", "CreatedAt", "Currency", "DestinationCode", "DisplayPrice", "IsActive", "OriginCode", "SortOrder", "UpdatedAt")
    VALUES (2, TIMESTAMP '2026-04-15T21:49:05.969047', 'TRY', 'ADB', 749.0, TRUE, 'IST', 2, NULL);
    INSERT INTO "PopularRoutes" ("Id", "CreatedAt", "Currency", "DestinationCode", "DisplayPrice", "IsActive", "OriginCode", "SortOrder", "UpdatedAt")
    VALUES (3, TIMESTAMP '2026-04-15T21:49:05.969047', 'TRY', 'TZX', 699.0, TRUE, 'IST', 3, NULL);
    INSERT INTO "PopularRoutes" ("Id", "CreatedAt", "Currency", "DestinationCode", "DisplayPrice", "IsActive", "OriginCode", "SortOrder", "UpdatedAt")
    VALUES (4, TIMESTAMP '2026-04-15T21:49:05.969047', 'TRY', 'IST', 599.0, TRUE, 'ESB', 4, NULL);
    INSERT INTO "PopularRoutes" ("Id", "CreatedAt", "Currency", "DestinationCode", "DisplayPrice", "IsActive", "OriginCode", "SortOrder", "UpdatedAt")
    VALUES (5, TIMESTAMP '2026-04-15T21:49:05.969047', 'TRY', 'BJV', 949.0, TRUE, 'IST', 5, NULL);
    INSERT INTO "PopularRoutes" ("Id", "CreatedAt", "Currency", "DestinationCode", "DisplayPrice", "IsActive", "OriginCode", "SortOrder", "UpdatedAt")
    VALUES (6, TIMESTAMP '2026-04-15T21:49:05.969047', 'TRY', 'AYT', 799.0, TRUE, 'ESB', 6, NULL);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    INSERT INTO "BookingClasses" ("Id", "Code", "FareTypeId", "IsChangeable", "IsRefundable", "NameEn", "NameTr", "SortOrder")
    VALUES (1, 'Y', 1, TRUE, TRUE, 'Economy Full', 'Ekonomi Full', 1);
    INSERT INTO "BookingClasses" ("Id", "Code", "FareTypeId", "IsChangeable", "IsRefundable", "NameEn", "NameTr", "SortOrder")
    VALUES (2, 'M', 1, TRUE, TRUE, 'Economy Flexible', 'Ekonomi Esnek', 2);
    INSERT INTO "BookingClasses" ("Id", "Code", "FareTypeId", "IsChangeable", "IsRefundable", "NameEn", "NameTr", "SortOrder")
    VALUES (3, 'S', 1, TRUE, FALSE, 'Economy Restricted', 'Ekonomi Kısıtlı', 3);
    INSERT INTO "BookingClasses" ("Id", "Code", "FareTypeId", "IsChangeable", "IsRefundable", "NameEn", "NameTr", "SortOrder")
    VALUES (4, 'V', 1, FALSE, FALSE, 'Economy Discounted', 'Ekonomi İndirimli', 4);
    INSERT INTO "BookingClasses" ("Id", "Code", "FareTypeId", "IsChangeable", "IsRefundable", "NameEn", "NameTr", "SortOrder")
    VALUES (5, 'C', 3, TRUE, TRUE, 'Business Full', 'Business Full', 5);
    INSERT INTO "BookingClasses" ("Id", "Code", "FareTypeId", "IsChangeable", "IsRefundable", "NameEn", "NameTr", "SortOrder")
    VALUES (6, 'J', 3, TRUE, TRUE, 'Business Discounted', 'Business İndirimli', 6);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_Airlines_Code" ON "Airlines" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Airports_CountryCode" ON "Airports" ("CountryCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_Airports_IataCode" ON "Airports" ("IataCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Airports_IsDomestic" ON "Airports" ("IsDomestic");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Airports_IsPopular" ON "Airports" ("IsPopular");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_BillingInfo_BookingId" ON "BillingInfo" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_BookingClasses_Code" ON "BookingClasses" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_BookingClasses_FareTypeId" ON "BookingClasses" ("FareTypeId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_BookingLogs_BookingId" ON "BookingLogs" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_BookingLogs_CreatedAt" ON "BookingLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_BookingLogs_Operation" ON "BookingLogs" ("Operation");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_BookingLogs_UserId" ON "BookingLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Bookings_GuestSessionId" ON "Bookings" ("GuestSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Bookings_PNR" ON "Bookings" ("PNR");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Bookings_Status" ON "Bookings" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Bookings_UserId" ON "Bookings" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_FareDetails_BookingId" ON "FareDetails" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_FareTypes_Code" ON "FareTypes" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_FlightSegments_BookingId" ON "FlightSegments" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_GuestSessions_Email" ON "GuestSessions" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Passengers_BookingId" ON "Passengers" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Payments_BookingId" ON "Payments" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_SearchLogs_CreatedAt" ON "SearchLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_SearchLogs_SessionId" ON "SearchLogs" ("SessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Sessions_UserId" ON "Sessions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_SystemLogs_Action" ON "SystemLogs" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_SystemLogs_CreatedAt" ON "SystemLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_SystemLogs_UserId" ON "SystemLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_TripBookings_BookingId" ON "TripBookings" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_TripBookings_TripId" ON "TripBookings" ("TripId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_TripPassengers_PassengerId" ON "TripPassengers" ("PassengerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_TripPassengers_TripId" ON "TripPassengers" ("TripId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE INDEX "IX_Trips_UserId" ON "Trips" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_Users_CustomerNumber" ON "Users" ("CustomerNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Airlines"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Airlines") + 1,
            nextval(pg_get_serial_sequence('"Airlines"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"FareTypes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "FareTypes") + 1,
            nextval(pg_get_serial_sequence('"FareTypes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"PopularRoutes"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "PopularRoutes") + 1,
            nextval(pg_get_serial_sequence('"PopularRoutes"', 'Id'))),
        false);
    PERFORM setval(
        pg_get_serial_sequence('"BookingClasses"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "BookingClasses") + 1,
            nextval(pg_get_serial_sequence('"BookingClasses"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260415214906_AddInternalPnr') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260415214906_AddInternalPnr', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE TABLE "AdminUsers" (
        "Id" uuid NOT NULL,
        "Username" character varying(64) NOT NULL,
        "Email" character varying(256) NOT NULL,
        "FullName" character varying(128) NOT NULL,
        "PasswordHash" character varying(256) NOT NULL,
        "Role" integer NOT NULL,
        "TwoFactorSecret" character varying(64),
        "TwoFactorEnabled" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "LockedUntil" timestamp without time zone,
        "FailedLoginAttempts" integer NOT NULL,
        "LastLoginAt" timestamp without time zone,
        "LastLoginIp" character varying(64),
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone,
        CONSTRAINT "PK_AdminUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE TABLE "AdminAuditLogs" (
        "Id" uuid NOT NULL,
        "AdminUserId" uuid,
        "Username" character varying(64),
        "Action" character varying(128) NOT NULL,
        "TargetEntity" character varying(64),
        "TargetId" character varying(64),
        "Details" text,
        "Success" boolean NOT NULL,
        "ErrorMessage" character varying(1024),
        "IpAddress" character varying(64),
        "UserAgent" character varying(512),
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_AdminAuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdminAuditLogs_AdminUsers_AdminUserId" FOREIGN KEY ("AdminUserId") REFERENCES "AdminUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE TABLE "AdminRefreshTokens" (
        "Id" uuid NOT NULL,
        "AdminUserId" uuid NOT NULL,
        "TokenHash" character varying(128) NOT NULL,
        "ExpiresAt" timestamp without time zone NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "CreatedByIp" character varying(64),
        "UserAgent" character varying(512),
        "RevokedAt" timestamp without time zone,
        "RevokedByIp" character varying(64),
        "RevokedReason" character varying(64),
        "ReplacedByTokenId" uuid,
        CONSTRAINT "PK_AdminRefreshTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AdminRefreshTokens_AdminUsers_AdminUserId" FOREIGN KEY ("AdminUserId") REFERENCES "AdminUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.631979'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.63198'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.63198'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.63198'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.63198'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.63198'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.63198'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.631981'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.631981'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.631981'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.632004'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.632005'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.632005'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.632005'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.632005'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-19T13:04:37.632005'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE INDEX "IX_AdminAuditLogs_Action" ON "AdminAuditLogs" ("Action");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE INDEX "IX_AdminAuditLogs_AdminUserId" ON "AdminAuditLogs" ("AdminUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE INDEX "IX_AdminAuditLogs_CreatedAt" ON "AdminAuditLogs" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE INDEX "IX_AdminRefreshTokens_AdminUserId_RevokedAt_ExpiresAt" ON "AdminRefreshTokens" ("AdminUserId", "RevokedAt", "ExpiresAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE UNIQUE INDEX "IX_AdminRefreshTokens_TokenHash" ON "AdminRefreshTokens" ("TokenHash");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE UNIQUE INDEX "IX_AdminUsers_Email" ON "AdminUsers" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    CREATE UNIQUE INDEX "IX_AdminUsers_Username" ON "AdminUsers" ("Username");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260419130438_AddAdminEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260419130438_AddAdminEntities', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    ALTER TABLE "Payments" ADD "BiletBankPaymentId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    ALTER TABLE "Payments" ADD "ErrorCode" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    ALTER TABLE "Payments" ADD "PaymentType" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    ALTER TABLE "Payments" ADD "RawRequest" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    ALTER TABLE "Payments" ADD "RawResponse" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945958'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945959'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945959'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945959'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945959'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945959'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.94596'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.94596'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.94596'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.94596'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945983'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945984'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945984'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945984'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945984'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-21T12:02:11.945984'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260421120212_AddPaymentProviderFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260421120212_AddPaymentProviderFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE TABLE "SupportTickets" (
        "Id" uuid NOT NULL,
        "TicketNumber" character varying(32) NOT NULL,
        "UserId" uuid NOT NULL,
        "BookingId" uuid,
        "Type" integer NOT NULL,
        "Subject" character varying(200) NOT NULL,
        "Status" integer NOT NULL,
        "ClosedAt" timestamp without time zone,
        "ClosedByAdminId" uuid,
        "LastActivityAt" timestamp without time zone NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        "UpdatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SupportTickets" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupportTickets_AdminUsers_ClosedByAdminId" FOREIGN KEY ("ClosedByAdminId") REFERENCES "AdminUsers" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_SupportTickets_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_SupportTickets_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE TABLE "SupportTicketMessages" (
        "Id" uuid NOT NULL,
        "TicketId" uuid NOT NULL,
        "SenderType" integer NOT NULL,
        "SenderId" uuid NOT NULL,
        "SenderDisplayName" character varying(128) NOT NULL,
        "Body" text NOT NULL,
        "CreatedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_SupportTicketMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SupportTicketMessages_SupportTickets_TicketId" FOREIGN KEY ("TicketId") REFERENCES "SupportTickets" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855135'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855136'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855136'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855136'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855136'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855136'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855137'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855137'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855137'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855137'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855181'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855181'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855182'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855182'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855182'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-22T11:35:41.855182'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTicketMessages_CreatedAt" ON "SupportTicketMessages" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTicketMessages_TicketId" ON "SupportTicketMessages" ("TicketId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_BookingId" ON "SupportTickets" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_ClosedByAdminId" ON "SupportTickets" ("ClosedByAdminId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_CreatedAt" ON "SupportTickets" ("CreatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_LastActivityAt" ON "SupportTickets" ("LastActivityAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_Status" ON "SupportTickets" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE UNIQUE INDEX "IX_SupportTickets_TicketNumber" ON "SupportTickets" ("TicketNumber");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_Type" ON "SupportTickets" ("Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    CREATE INDEX "IX_SupportTickets_UserId" ON "SupportTickets" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260422113542_AddSupportTicketSystem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260422113542_AddSupportTicketSystem', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    ALTER TABLE "SupportTickets" ALTER COLUMN "UserId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    ALTER TABLE "SupportTickets" ADD "GuestSessionId" uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    ALTER TABLE "SupportTicketMessages" ALTER COLUMN "SenderId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895042'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895043'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895043'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895043'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895043'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895043'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895043'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895044'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895044'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895044'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895075'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895076'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895076'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895076'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895076'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-23T11:37:09.895076'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    CREATE INDEX "IX_SupportTickets_GuestSessionId" ON "SupportTickets" ("GuestSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    ALTER TABLE "SupportTickets" ADD CONSTRAINT "FK_SupportTickets_GuestSessions_GuestSessionId" FOREIGN KEY ("GuestSessionId") REFERENCES "GuestSessions" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423113710_SupportTicketGuestSupport') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260423113710_SupportTicketGuestSupport', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    ALTER TABLE "Bookings" ADD "TicketTimeLimit" timestamp without time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.22493'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224931'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224931'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224931'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224931'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224931'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224932'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224932'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224932'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.224932'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.225055'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.225056'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.225056'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.225056'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.225056'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T09:53:46.225056'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429095347_AddTicketTimeLimit') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260429095347_AddTicketTimeLimit', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    ALTER TABLE "Bookings" ADD "PaymentAttemptCount" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    ALTER TABLE "Bookings" ADD "ProductId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    ALTER TABLE "Bookings" ADD "ShoppingFileId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968067'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968068'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968068'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968068'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968068'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968068'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968069'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968069'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968069'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968069'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968124'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968124'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968124'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968125'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968125'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:10:32.968125'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429101033_AddBookingRetryFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260429101033_AddBookingRetryFields', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    ALTER TABLE "Payments" DROP CONSTRAINT "FK_Payments_Bookings_BookingId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    ALTER TABLE "Payments" ALTER COLUMN "BookingId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501198'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501199'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501199'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501199'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501199'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501199'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501199'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.5012'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.5012'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.5012'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501222'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501223'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501223'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501223'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501223'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-04-29T10:25:14.501223'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    ALTER TABLE "Payments" ADD CONSTRAINT "FK_Payments_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260429102515_MakePaymentBookingIdNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260429102515_MakePaymentBookingIdNullable', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    ALTER TABLE "SupportTickets" ADD "GuestEmail" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480597'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480598'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480598'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480598'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480598'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480598'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480598'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480599'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480599'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480599'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480637'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480638'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480638'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480638'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480638'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-06T14:39:24.480638'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506143925_AddSupportTicketGuestEmail') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260506143925_AddSupportTicketGuestEmail', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    CREATE TABLE "BookingChangeLogs" (
        "Id" uuid NOT NULL,
        "BookingId" uuid NOT NULL,
        "FieldName" text NOT NULL,
        "OldValue" text,
        "NewValue" text,
        "ChangedByAdminId" uuid,
        "ChangedAt" timestamp without time zone NOT NULL,
        CONSTRAINT "PK_BookingChangeLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_BookingChangeLogs_Bookings_BookingId" FOREIGN KEY ("BookingId") REFERENCES "Bookings" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067457'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067458'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067458'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067458'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067458'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067458'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067459'
    WHERE "Id" = 7;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067459'
    WHERE "Id" = 8;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067459'
    WHERE "Id" = 9;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "Airlines" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067459'
    WHERE "Id" = 10;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067496'
    WHERE "Id" = 1;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067496'
    WHERE "Id" = 2;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067497'
    WHERE "Id" = 3;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067497'
    WHERE "Id" = 4;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067497'
    WHERE "Id" = 5;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    UPDATE "PopularRoutes" SET "CreatedAt" = TIMESTAMP '2026-05-13T09:42:19.067497'
    WHERE "Id" = 6;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    CREATE INDEX "IX_BookingChangeLogs_BookingId" ON "BookingChangeLogs" ("BookingId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260513094219_AddBookingChangeLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260513094219_AddBookingChangeLog', '8.0.0');
    END IF;
END $EF$;
COMMIT;

