// <auto-generated />
using System;
using GBILET.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GBILET.Infrastructure.Migrations
{
    [DbContext(typeof(GTicketDbContext))]
    [Migration("20260429101033_AddBookingRetryFields")]
    partial class AddBookingRetryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GBILET.Core.Entities.Admin.AdminAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetEntity")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TargetId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("AdminUserId");

                    b.HasIndex("CreatedAt");

                    b.ToTable("AdminAuditLogs", (string)null);
                });

            modelBuilder.Entity("GBILET.Core.Entities.Admin.AdminRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdminUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AdminUserId", "RevokedAt", "ExpiresAt");

                    b.ToTable("AdminRefreshTokens", (string)null);
                });

            modelBuilder.Entity("GBILET.Core.Entities.Admin.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TwoFactorSecret")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("GBILET.Core.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alliance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDomestic")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alliance = "Star Alliance",
                            Code = "TK",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(679),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/tk.png",
                            NameEn = "Turkish Airlines",
                            NameTr = "Türk Hava Yolları",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PC",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(684),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/pc.png",
                            NameEn = "Pegasus Airlines",
                            NameTr = "Pegasus Hava Yolları",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "VF",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(686),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/vf.png",
                            NameEn = "AnadoluJet",
                            NameTr = "AnadoluJet",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "XQ",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(687),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/xq.png",
                            NameEn = "SunExpress",
                            NameTr = "SunExpress",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "XC",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(688),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/xc.png",
                            NameEn = "Corendon Airlines",
                            NameTr = "Corendon Airlines",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Alliance = "Star Alliance",
                            Code = "LH",
                            CountryCode = "DE",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(689),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/lh.png",
                            NameEn = "Lufthansa",
                            NameTr = "Lufthansa",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 7,
                            Alliance = "Oneworld",
                            Code = "BA",
                            CountryCode = "GB",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(691),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/ba.png",
                            NameEn = "British Airways",
                            NameTr = "British Airways",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 8,
                            Alliance = "SkyTeam",
                            Code = "AF",
                            CountryCode = "FR",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(692),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/af.png",
                            NameEn = "Air France",
                            NameTr = "Air France",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 9,
                            Code = "EK",
                            CountryCode = "AE",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(694),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/ek.png",
                            NameEn = "Emirates",
                            NameTr = "Emirates",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 10,
                            Alliance = "Oneworld",
                            Code = "QR",
                            CountryCode = "QA",
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(695),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/qr.png",
                            NameEn = "Qatar Airways",
                            NameTr = "Qatar Airways",
                            SortOrder = 14
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("CityEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CityTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CountryEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IcaoCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCity")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDomestic")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPopular")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.HasIndex("IsDomestic");

                    b.HasIndex("IsPopular");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BillingInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressCity")
                        .HasColumnType("text");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text");

                    b.Property<string>("AddressDistrict")
                        .HasColumnType("text");

                    b.Property<string>("AddressZipCode")
                        .HasColumnType("text");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxNo")
                        .HasColumnType("text");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("BillingInfo");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<string>("AirlineCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("AllocatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("BiletBankFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("InfantCount")
                        .HasColumnType("integer");

                    b.Property<string>("InternalPnr")
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("OurCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PNR")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("PaymentAttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProductId")
                        .HasColumnType("text");

                    b.Property<string>("ProductItemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShoppingFileId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TicketTimeLimit")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TicketedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("PNR");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("FareTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChangeable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FareTypeId");

                    b.ToTable("BookingClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Y",
                            FareTypeId = 1,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Economy Full",
                            NameTr = "Ekonomi Full",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "M",
                            FareTypeId = 1,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Economy Flexible",
                            NameTr = "Ekonomi Esnek",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "S",
                            FareTypeId = 1,
                            IsChangeable = true,
                            IsRefundable = false,
                            NameEn = "Economy Restricted",
                            NameTr = "Ekonomi Kısıtlı",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "V",
                            FareTypeId = 1,
                            IsChangeable = false,
                            IsRefundable = false,
                            NameEn = "Economy Discounted",
                            NameTr = "Ekonomi İndirimli",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "C",
                            FareTypeId = 3,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Business Full",
                            NameTr = "Business Full",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "J",
                            FareTypeId = 3,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Business Discounted",
                            NameTr = "Business İndirimli",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Operation");

                    b.HasIndex("UserId");

                    b.ToTable("BookingLogs");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BiletBankCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OurPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("FareDetails");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FareTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ECO",
                            IsActive = true,
                            NameEn = "Economy",
                            NameTr = "Ekonomi",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PEF",
                            IsActive = true,
                            NameEn = "Premium Economy",
                            NameTr = "Premium Ekonomi",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "BUS",
                            IsActive = true,
                            NameEn = "Business",
                            NameTr = "Business",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "FIR",
                            IsActive = true,
                            NameEn = "First Class",
                            NameTr = "First Class",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.FlightSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("text");

                    b.Property<string>("Baggage")
                        .HasColumnType("text");

                    b.Property<string>("BookingClass")
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cabin")
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<string>("FareBasis")
                        .HasColumnType("text");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketingAirline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingAirline")
                        .HasColumnType("text");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("FlightSegments");
                });

            modelBuilder.Entity("GBILET.Core.Entities.GuestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("GuestSessions");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenNo")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesCode")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("PassportCountry")
                        .HasColumnType("text");

                    b.Property<string>("PassportNo")
                        .HasColumnType("text");

                    b.Property<string>("PaxReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("TempTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BiletBankPaymentId")
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardHolder")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("text");

                    b.Property<string>("CardLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Is3DSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("MaskedCardNumber")
                        .HasColumnType("text");

                    b.Property<string>("PaymentType")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RawRequest")
                        .HasColumnType("text");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GBILET.Core.Entities.PopularRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("DisplayPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("PopularRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(1241),
                            Currency = "TRY",
                            DestinationCode = "AYT",
                            DisplayPrice = 899.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(1247),
                            Currency = "TRY",
                            DestinationCode = "ADB",
                            DisplayPrice = 749.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(1248),
                            Currency = "TRY",
                            DestinationCode = "TZX",
                            DisplayPrice = 699.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(1250),
                            Currency = "TRY",
                            DestinationCode = "IST",
                            DisplayPrice = 599.00m,
                            IsActive = true,
                            OriginCode = "ESB",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(1251),
                            Currency = "TRY",
                            DestinationCode = "BJV",
                            DisplayPrice = 949.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 29, 10, 10, 32, 968, DateTimeKind.Utc).AddTicks(1252),
                            Currency = "TRY",
                            DestinationCode = "AYT",
                            DisplayPrice = 799.00m,
                            IsActive = true,
                            OriginCode = "ESB",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.SearchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FlightClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FlightType")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("HasError")
                        .HasColumnType("boolean");

                    b.Property<int>("InfantCount")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiletBankSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BiletBankSessionToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ShoppingFileId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Support.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ClosedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("GuestSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ClosedByAdminId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GuestSessionId");

                    b.HasIndex("LastActivityAt");

                    b.HasIndex("Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets", (string)null);
                });

            modelBuilder.Entity("GBILET.Core.Entities.Support.SupportTicketMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SenderDisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<int>("SenderType")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TicketId");

                    b.ToTable("SupportTicketMessages", (string)null);
                });

            modelBuilder.Entity("GBILET.Core.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("integer");

                    b.Property<string>("TripName")
                        .HasColumnType("text");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TripId");

                    b.ToTable("TripBookings");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.ToTable("TripPassengers");
                });

            modelBuilder.Entity("GBILET.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Admin.AdminAuditLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Admin.AdminUser", "AdminUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Admin.AdminRefreshToken", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Admin.AdminUser", "AdminUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BillingInfo", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithOne("BillingInfo")
                        .HasForeignKey("GBILET.Core.Entities.BillingInfo", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Booking", b =>
                {
                    b.HasOne("GBILET.Core.Entities.GuestSession", "GuestSession")
                        .WithMany("Bookings")
                        .HasForeignKey("GuestSessionId");

                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("GuestSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingClass", b =>
                {
                    b.HasOne("GBILET.Core.Entities.FareType", "FareType")
                        .WithMany("BookingClasses")
                        .HasForeignKey("FareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FareType");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("BookingLogs")
                        .HasForeignKey("BookingId");

                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareDetail", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("FareDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FlightSegment", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("FlightSegments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Passenger", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Payment", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.SearchLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Session", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Support.SupportTicket", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GBILET.Core.Entities.Admin.AdminUser", "ClosedByAdmin")
                        .WithMany()
                        .HasForeignKey("ClosedByAdminId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GBILET.Core.Entities.GuestSession", null)
                        .WithMany()
                        .HasForeignKey("GuestSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Booking");

                    b.Navigation("ClosedByAdmin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Support.SupportTicketMessage", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Support.SupportTicket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("GBILET.Core.Entities.SystemLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Trip", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripBooking", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBILET.Core.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripPassenger", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBILET.Core.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Admin.AdminUser", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Booking", b =>
                {
                    b.Navigation("BillingInfo");

                    b.Navigation("BookingLogs");

                    b.Navigation("FareDetails");

                    b.Navigation("FlightSegments");

                    b.Navigation("Passengers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareType", b =>
                {
                    b.Navigation("BookingClasses");
                });

            modelBuilder.Entity("GBILET.Core.Entities.GuestSession", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Support.SupportTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
