// <auto-generated />
using System;
using GBILET.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GBILET.Infrastructure.Migrations
{
    [DbContext(typeof(GTicketDbContext))]
    [Migration("20260315214250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GBILET.Core.Entities.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alliance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDomestic")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alliance = "Star Alliance",
                            Code = "TK",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6114),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/tk.png",
                            NameEn = "Turkish Airlines",
                            NameTr = "Türk Hava Yolları",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PC",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6117),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/pc.png",
                            NameEn = "Pegasus Airlines",
                            NameTr = "Pegasus Hava Yolları",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "VF",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6118),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/vf.png",
                            NameEn = "AnadoluJet",
                            NameTr = "AnadoluJet",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "XQ",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6120),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/xq.png",
                            NameEn = "SunExpress",
                            NameTr = "SunExpress",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "XC",
                            CountryCode = "TR",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6121),
                            IsActive = true,
                            IsDomestic = true,
                            LogoUrl = "/assets/airlines/xc.png",
                            NameEn = "Corendon Airlines",
                            NameTr = "Corendon Airlines",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Alliance = "Star Alliance",
                            Code = "LH",
                            CountryCode = "DE",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6122),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/lh.png",
                            NameEn = "Lufthansa",
                            NameTr = "Lufthansa",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 7,
                            Alliance = "Oneworld",
                            Code = "BA",
                            CountryCode = "GB",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6124),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/ba.png",
                            NameEn = "British Airways",
                            NameTr = "British Airways",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 8,
                            Alliance = "SkyTeam",
                            Code = "AF",
                            CountryCode = "FR",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6125),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/af.png",
                            NameEn = "Air France",
                            NameTr = "Air France",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 9,
                            Code = "EK",
                            CountryCode = "AE",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6126),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/ek.png",
                            NameEn = "Emirates",
                            NameTr = "Emirates",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 10,
                            Alliance = "Oneworld",
                            Code = "QR",
                            CountryCode = "QA",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6128),
                            IsActive = true,
                            IsDomestic = false,
                            LogoUrl = "/assets/airlines/qr.png",
                            NameEn = "Qatar Airways",
                            NameTr = "Qatar Airways",
                            SortOrder = 14
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CityEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CityTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("CountryEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CountryTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IataCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("IcaoCode")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCity")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDomestic")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IataCode")
                        .IsUnique();

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityEn = "Istanbul",
                            CityTr = "İstanbul",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5691),
                            IataCode = "IST",
                            IcaoCode = "LTFM",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Istanbul Airport",
                            NameTr = "İstanbul Havalimanı",
                            SortOrder = 1,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 2,
                            CityEn = "Istanbul",
                            CityTr = "İstanbul",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5697),
                            IataCode = "SAW",
                            IcaoCode = "LTFJ",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Sabiha Gokcen Airport",
                            NameTr = "Sabiha Gökçen Havalimanı",
                            SortOrder = 2,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 3,
                            CityEn = "Ankara",
                            CityTr = "Ankara",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5699),
                            IataCode = "ESB",
                            IcaoCode = "LTAC",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Esenboga Airport",
                            NameTr = "Esenboğa Havalimanı",
                            SortOrder = 3,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 4,
                            CityEn = "Izmir",
                            CityTr = "İzmir",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5701),
                            IataCode = "ADB",
                            IcaoCode = "LTBJ",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Adnan Menderes Airport",
                            NameTr = "Adnan Menderes Havalimanı",
                            SortOrder = 4,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 5,
                            CityEn = "Antalya",
                            CityTr = "Antalya",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5703),
                            IataCode = "AYT",
                            IcaoCode = "LTAI",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Antalya Airport",
                            NameTr = "Antalya Havalimanı",
                            SortOrder = 5,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 6,
                            CityEn = "Trabzon",
                            CityTr = "Trabzon",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5705),
                            IataCode = "TZX",
                            IcaoCode = "LTCG",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Trabzon Airport",
                            NameTr = "Trabzon Havalimanı",
                            SortOrder = 6,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 7,
                            CityEn = "Mugla",
                            CityTr = "Muğla",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5707),
                            IataCode = "BJV",
                            IcaoCode = "LTFE",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Milas-Bodrum Airport",
                            NameTr = "Milas-Bodrum Havalimanı",
                            SortOrder = 7,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 8,
                            CityEn = "Mugla",
                            CityTr = "Muğla",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5709),
                            IataCode = "DLM",
                            IcaoCode = "LTBS",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Dalaman Airport",
                            NameTr = "Dalaman Havalimanı",
                            SortOrder = 8,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 9,
                            CityEn = "Gaziantep",
                            CityTr = "Gaziantep",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5711),
                            IataCode = "GZT",
                            IcaoCode = "LTAJ",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Gaziantep Airport",
                            NameTr = "Gaziantep Havalimanı",
                            SortOrder = 9,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 10,
                            CityEn = "Kayseri",
                            CityTr = "Kayseri",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5714),
                            IataCode = "ASR",
                            IcaoCode = "LTAP",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Kayseri Airport",
                            NameTr = "Kayseri Havalimanı",
                            SortOrder = 10,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 11,
                            CityEn = "Van",
                            CityTr = "Van",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5716),
                            IataCode = "VAN",
                            IcaoCode = "LTCI",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Van Ferit Melen Airport",
                            NameTr = "Van Ferit Melen Havalimanı",
                            SortOrder = 11,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 12,
                            CityEn = "Diyarbakir",
                            CityTr = "Diyarbakır",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5718),
                            IataCode = "DIY",
                            IcaoCode = "LTCC",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Diyarbakir Airport",
                            NameTr = "Diyarbakır Havalimanı",
                            SortOrder = 12,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 13,
                            CityEn = "Samsun",
                            CityTr = "Samsun",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5720),
                            IataCode = "SZF",
                            IcaoCode = "LTFH",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Samsun-Carsamba Airport",
                            NameTr = "Samsun-Çarşamba Havalimanı",
                            SortOrder = 13,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 14,
                            CityEn = "Erzurum",
                            CityTr = "Erzurum",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5722),
                            IataCode = "ERZ",
                            IcaoCode = "LTCE",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Erzurum Airport",
                            NameTr = "Erzurum Havalimanı",
                            SortOrder = 14,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 15,
                            CityEn = "Konya",
                            CityTr = "Konya",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5724),
                            IataCode = "KYA",
                            IcaoCode = "LTAN",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Konya Airport",
                            NameTr = "Konya Havalimanı",
                            SortOrder = 15,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 16,
                            CityEn = "Malatya",
                            CityTr = "Malatya",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5726),
                            IataCode = "MLX",
                            IcaoCode = "LTAT",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Malatya Airport",
                            NameTr = "Malatya Havalimanı",
                            SortOrder = 16,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 17,
                            CityEn = "Elazig",
                            CityTr = "Elazığ",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5728),
                            IataCode = "EZS",
                            IcaoCode = "LTCA",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Elazig Airport",
                            NameTr = "Elazığ Havalimanı",
                            SortOrder = 17,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 18,
                            CityEn = "Ordu",
                            CityTr = "Ordu",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5730),
                            IataCode = "OGU",
                            IcaoCode = "LTCN",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Ordu-Giresun Airport",
                            NameTr = "Ordu-Giresun Havalimanı",
                            SortOrder = 18,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 19,
                            CityEn = "Hatay",
                            CityTr = "Hatay",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5732),
                            IataCode = "HTY",
                            IcaoCode = "LTDA",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Hatay Airport",
                            NameTr = "Hatay Havalimanı",
                            SortOrder = 19,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 20,
                            CityEn = "Nevsehir",
                            CityTr = "Nevşehir",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5735),
                            IataCode = "NAV",
                            IcaoCode = "LTAZ",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Nevsehir Cappadocia Airport",
                            NameTr = "Nevşehir Kapadokya Havalimanı",
                            SortOrder = 20,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 21,
                            CityEn = "Eskisehir",
                            CityTr = "Eskişehir",
                            CountryCode = "TR",
                            CountryEn = "Turkey",
                            CountryTr = "Türkiye",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5737),
                            IataCode = "AOE",
                            IcaoCode = "LTBY",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = true,
                            NameEn = "Eskisehir Anadolu Airport",
                            NameTr = "Eskişehir Anadolu Havalimanı",
                            SortOrder = 21,
                            Timezone = "Europe/Istanbul"
                        },
                        new
                        {
                            Id = 22,
                            CityEn = "London",
                            CityTr = "Londra",
                            CountryCode = "GB",
                            CountryEn = "United Kingdom",
                            CountryTr = "İngiltere",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5739),
                            IataCode = "LHR",
                            IcaoCode = "EGLL",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = false,
                            NameEn = "London Heathrow Airport",
                            NameTr = "Londra Heathrow Havalimanı",
                            SortOrder = 100,
                            Timezone = "Europe/London"
                        },
                        new
                        {
                            Id = 23,
                            CityEn = "Paris",
                            CityTr = "Paris",
                            CountryCode = "FR",
                            CountryEn = "France",
                            CountryTr = "Fransa",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5741),
                            IataCode = "CDG",
                            IcaoCode = "LFPG",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = false,
                            NameEn = "Paris Charles de Gaulle Airport",
                            NameTr = "Paris Charles de Gaulle Havalimanı",
                            SortOrder = 101,
                            Timezone = "Europe/Paris"
                        },
                        new
                        {
                            Id = 24,
                            CityEn = "Frankfurt",
                            CityTr = "Frankfurt",
                            CountryCode = "DE",
                            CountryEn = "Germany",
                            CountryTr = "Almanya",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5743),
                            IataCode = "FRA",
                            IcaoCode = "EDDF",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = false,
                            NameEn = "Frankfurt Airport",
                            NameTr = "Frankfurt Havalimanı",
                            SortOrder = 102,
                            Timezone = "Europe/Berlin"
                        },
                        new
                        {
                            Id = 25,
                            CityEn = "Amsterdam",
                            CityTr = "Amsterdam",
                            CountryCode = "NL",
                            CountryEn = "Netherlands",
                            CountryTr = "Hollanda",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5745),
                            IataCode = "AMS",
                            IcaoCode = "EHAM",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = false,
                            NameEn = "Amsterdam Schiphol Airport",
                            NameTr = "Amsterdam Schiphol Havalimanı",
                            SortOrder = 103,
                            Timezone = "Europe/Amsterdam"
                        },
                        new
                        {
                            Id = 26,
                            CityEn = "Dubai",
                            CityTr = "Dubai",
                            CountryCode = "AE",
                            CountryEn = "United Arab Emirates",
                            CountryTr = "Birleşik Arap Emirlikleri",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5747),
                            IataCode = "DXB",
                            IcaoCode = "OMDB",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = false,
                            NameEn = "Dubai International Airport",
                            NameTr = "Dubai Uluslararası Havalimanı",
                            SortOrder = 104,
                            Timezone = "Asia/Dubai"
                        },
                        new
                        {
                            Id = 27,
                            CityEn = "New York",
                            CityTr = "New York",
                            CountryCode = "US",
                            CountryEn = "United States",
                            CountryTr = "Amerika Birleşik Devletleri",
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(5750),
                            IataCode = "JFK",
                            IcaoCode = "KJFK",
                            IsActive = true,
                            IsCity = false,
                            IsDomestic = false,
                            NameEn = "John F. Kennedy International Airport",
                            NameTr = "New York JFK Havalimanı",
                            SortOrder = 105,
                            Timezone = "America/New_York"
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.BillingInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressCity")
                        .HasColumnType("text");

                    b.Property<string>("AddressDetail")
                        .HasColumnType("text");

                    b.Property<string>("AddressDistrict")
                        .HasColumnType("text");

                    b.Property<string>("AddressZipCode")
                        .HasColumnType("text");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .HasColumnType("text");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxNo")
                        .HasColumnType("text");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("BillingInfo");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<string>("AirlineCode")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime?>("AllocatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("BiletBankFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Destination")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("FlightNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("GrandTotal")
                        .HasColumnType("numeric");

                    b.Property<int>("InfantCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal>("OurCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PNR")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProductItemId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TicketedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PNR");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int>("FareTypeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChangeable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRefundable")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("FareTypeId");

                    b.ToTable("BookingClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Y",
                            FareTypeId = 1,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Economy Full",
                            NameTr = "Ekonomi Full",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "M",
                            FareTypeId = 1,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Economy Flexible",
                            NameTr = "Ekonomi Esnek",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "S",
                            FareTypeId = 1,
                            IsChangeable = true,
                            IsRefundable = false,
                            NameEn = "Economy Restricted",
                            NameTr = "Ekonomi Kısıtlı",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "V",
                            FareTypeId = 1,
                            IsChangeable = false,
                            IsRefundable = false,
                            NameEn = "Economy Discounted",
                            NameTr = "Ekonomi İndirimli",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "C",
                            FareTypeId = 3,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Business Full",
                            NameTr = "Business Full",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "J",
                            FareTypeId = 3,
                            IsChangeable = true,
                            IsRefundable = true,
                            NameEn = "Business Discounted",
                            NameTr = "Business İndirimli",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestBody")
                        .HasColumnType("text");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("SessionToken")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Operation");

                    b.HasIndex("UserId");

                    b.ToTable("BookingLogs");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("BiletBankCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OurPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Profit")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ServiceFee")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("FareDetails");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FareTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ECO",
                            IsActive = true,
                            NameEn = "Economy",
                            NameTr = "Ekonomi",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PEF",
                            IsActive = true,
                            NameEn = "Premium Economy",
                            NameTr = "Premium Ekonomi",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "BUS",
                            IsActive = true,
                            NameEn = "Business",
                            NameTr = "Business",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "FIR",
                            IsActive = true,
                            NameEn = "First Class",
                            NameTr = "First Class",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.FlightSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ArrivalTime")
                        .HasColumnType("text");

                    b.Property<string>("Baggage")
                        .HasColumnType("text");

                    b.Property<string>("BookingClass")
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cabin")
                        .HasColumnType("text");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartureTime")
                        .HasColumnType("text");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<string>("FareBasis")
                        .HasColumnType("text");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarketingAirline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingAirline")
                        .HasColumnType("text");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("TicketNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("FlightSegments");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Passenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CitizenNo")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesCode")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nationality")
                        .HasColumnType("text");

                    b.Property<string>("PassportCountry")
                        .HasColumnType("text");

                    b.Property<string>("PassportNo")
                        .HasColumnType("text");

                    b.Property<string>("PaxReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<string>("TempTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TicketNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<string>("CardHolder")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("text");

                    b.Property<string>("CardLastFour")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("InstallmentCount")
                        .HasColumnType("integer");

                    b.Property<bool>("Is3DSecure")
                        .HasColumnType("boolean");

                    b.Property<string>("MaskedCardNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProviderTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RedirectUrl")
                        .HasColumnType("text");

                    b.Property<decimal?>("RefundAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("GBILET.Core.Entities.PopularRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("DestinationCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("DisplayPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("OriginCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PopularRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6236),
                            Currency = "TRY",
                            DestinationCode = "AYT",
                            DisplayPrice = 899.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6243),
                            Currency = "TRY",
                            DestinationCode = "ADB",
                            DisplayPrice = 749.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6245),
                            Currency = "TRY",
                            DestinationCode = "TZX",
                            DisplayPrice = 699.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6246),
                            Currency = "TRY",
                            DestinationCode = "IST",
                            DisplayPrice = 599.00m,
                            IsActive = true,
                            OriginCode = "ESB",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6247),
                            Currency = "TRY",
                            DestinationCode = "BJV",
                            DisplayPrice = 949.00m,
                            IsActive = true,
                            OriginCode = "IST",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 15, 21, 42, 50, 377, DateTimeKind.Utc).AddTicks(6249),
                            Currency = "TRY",
                            DestinationCode = "AYT",
                            DisplayPrice = 799.00m,
                            IsActive = true,
                            OriginCode = "ESB",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("GBILET.Core.Entities.SearchLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdultCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChildCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FlightClass")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FlightType")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("HasError")
                        .HasColumnType("boolean");

                    b.Property<int>("InfantCount")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("MinPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SessionId");

                    b.ToTable("SearchLogs");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BiletBankSessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BiletBankSessionToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastActivityAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShoppingFileId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("GBILET.Core.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalPassengers")
                        .HasColumnType("integer");

                    b.Property<string>("TripName")
                        .HasColumnType("text");

                    b.Property<string>("TripType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TripId");

                    b.ToTable("TripBookings");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripPassenger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PassengerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PassengerId");

                    b.HasIndex("TripId");

                    b.ToTable("TripPassengers");
                });

            modelBuilder.Entity("GBILET.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BillingInfo", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithOne("BillingInfo")
                        .HasForeignKey("GBILET.Core.Entities.BillingInfo", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Booking", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingClass", b =>
                {
                    b.HasOne("GBILET.Core.Entities.FareType", "FareType")
                        .WithMany("BookingClasses")
                        .HasForeignKey("FareTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FareType");
                });

            modelBuilder.Entity("GBILET.Core.Entities.BookingLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("BookingLogs")
                        .HasForeignKey("BookingId");

                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareDetail", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("FareDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FlightSegment", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("FlightSegments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Passenger", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Payment", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("GBILET.Core.Entities.SearchLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Session", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.SystemLog", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Trip", b =>
                {
                    b.HasOne("GBILET.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripBooking", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBILET.Core.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GBILET.Core.Entities.TripPassenger", b =>
                {
                    b.HasOne("GBILET.Core.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GBILET.Core.Entities.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passenger");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("GBILET.Core.Entities.Booking", b =>
                {
                    b.Navigation("BillingInfo");

                    b.Navigation("BookingLogs");

                    b.Navigation("FareDetails");

                    b.Navigation("FlightSegments");

                    b.Navigation("Passengers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GBILET.Core.Entities.FareType", b =>
                {
                    b.Navigation("BookingClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
